# BC카드 추천 엔진 - 카테고리별 지출 기반 최적 카드 추천 서비스

## 1. 필요 라이브러리 및 데이터 불러오기

In [4]:
import pandas as pd
import numpy as np

In [5]:
df_benefit = pd.read_csv("bc_card_benefit_final_before_recommendation.csv")
df_benefit.head()

,card_name,benefit_title,benefit_category_final,benefit_type,benefit_rate_v2,all_previous_month_spend,monthly_limit_candidates,spend_limit_map,main_benefit,detail_url,raw_text,full_text
0,[BNK경남] 경남은행 K-패스 카드,모빌리티 할인 서비스(결제일 차감 청구),교통,할인,15.0,"[300000, 600000]","[6000, 8000]","{300000: 6000, 600000: 8000}",대중교통 요금 15% 할인,https://www.bccard.com/app/card/CreditCardMain...,모빌리티 할인 서비스(결제일 차감 청구)\n대중교통 요금 15% 할인 | 친환경 모...,"대중교통 요금 15% 할인\n대상 가맹점 : 버스(시내버스, 마을버스, 광역버스)지..."
1,[BNK경남] 경남은행 K-패스 카드,생활 할인 서비스(결제일 차감 청구),간편결제 / 구독 / 마트·편의점 / 반려동물 / 배달 / 여행·항공 / 의료 / ...,할인,5.0,"[10000, 20000, 300000, 600000]","[1500, 6000, 8000]",{},대중교통 요금 15% 할인,https://www.bccard.com/app/card/CreditCardMain...,"생활 할인 서비스(결제일 차감 청구)\n이동통신요금 5% 할인 (월 1회, 최대 1...","이동통신요금 5% 할인 (월 1회, 최대 1,500원 할인)\n대상 가맹점 : SK..."
2,[Sh수협] 더 아우름 카드,프리미엄 바우처 (Premium Voucher),간편결제 / 마트·편의점 / 문화·여가 / 쇼핑 / 아파트·공과금 / 여행·항공 /...,할인,NaN,"[200000, 1000000, 2000000]",[],{},프리미엄 바우처 제공,https://www.bccard.com/app/card/CreditCardMain...,프리미엄 바우처 (Premium Voucher)\n바우처 4가지 중 1가지를 선택하...,바우처 4가지 중 1가지를 선택하여 이용(연1회)\n프리미엄 바우처 안내\nHote...
3,[Sh수협] 더 아우름 카드,할인서비스,간편결제 / 교육 / 마트·편의점 / 문화·여가 / 반려동물 / 아파트·공과금 / ...,할인,5.0,"[10000, 500000, 1000000, 2000000]","[5000, 15000, 45000]",{},프리미엄 바우처 제공,https://www.bccard.com/app/card/CreditCardMain...,할인서비스\n라이프스타일 패키지(옵션 패키지 중 택1) | 할인 서비스 공통기준 |...,라이프스타일 패키지(옵션 패키지 중 택1)\n서비스 안내 : 라이프스타일에 따른 옵...
4,[BC바로] BC 바로 ZONE 카드,"EAT ZONE 커피, 간식, 배달앱 7% 할인",배달 / 카페,할인,7.0,"[300000, 600000]","[5000, 10000]","{300000: 5000, 600000: 10000}",온라인몰/커피/배달 7% 할인,https://www.bccard.com/app/card/CreditCardMain...,"EAT ZONE 커피, 간식, 배달앱 7% 할인\n\n커피, 간식 : 현장결제 또는...","카테고리별 가맹점, 월 할인 한도 안내표\n카테고리\n대상 가맹점\n월 할인 한도\..."

#### str > dict로 변경

In [13]:
import ast

def safe_eval(x):

    if pd.isna(x):
        return {}

    try:
        return ast.literal_eval(x)

    except:
        return {}

df_benefit["spend_limit_map"] = (
    df_benefit["spend_limit_map"]
    .apply(safe_eval)
)

In [14]:
type(df_benefit.iloc[0]["spend_limit_map"])

dict

## 2. 사용자 입력: 월 지출 총액 및 카테고리별 지출 입력

In [6]:
user_spending = {
    "교통": 80000,
    "카페": 70000,
    "외식": 150000,
    "배달": 120000,
    "마트·편의점": 100000,
    "쇼핑": 300000,
    "통신": 80000,
    "구독": 30000,
    "주유·충전": 0,
    "여행·항공": 0,
    "의료": 30000,
    "교육": 0,
    "문화·여가": 50000,
    "간편결제": 200000
}

total_monthly_spending = sum(user_spending.values())

print("월 총 소비금액:", total_monthly_spending)

월 총 소비금액: 1210000

## 3. 혜택 카테고리별 소비

In [7]:
def get_matched_spending(category_text):

    if pd.isna(category_text):
        return 0

    categories = [
        c.strip()
        for c in str(category_text).split("/")
    ]

    total = 0

    for category in categories:
        total += user_spending.get(category, 0)

    return total


df_benefit["matched_spending"] = (
    df_benefit["benefit_category_final"]
    .apply(get_matched_spending)
)

## 4. 카드별 예상 월간 혜택 금액 계산

In [8]:
def calculate_expected_benefit(row):

    spending = row["matched_spending"]

    rate = row["benefit_rate_v2"]

    limit_map = row["spend_limit_map"]

    # 할인율 없으면 0
    if pd.isna(rate):
        return 0

    # 기본 할인 계산
    expected = spending * (rate / 100)

    applicable_limit = None

    # =========================
    # 전월실적 조건 확인
    # =========================

    if isinstance(limit_map, dict):

        spend_conditions = []

        for k, v in limit_map.items():

            if isinstance(k, int):
                spend_conditions.append((k, v))

        # 높은 실적조건부터 검사
        spend_conditions = sorted(
            spend_conditions,
            reverse=True
        )

        for spend_condition, limit in spend_conditions:

            if total_monthly_spending >= spend_condition:
                applicable_limit = limit
                break

    # =========================
    # 한도 적용
    # =========================

    if applicable_limit is not None:
        expected = min(expected, applicable_limit)

    return round(expected)

## 5. 카드 계산 적용

In [9]:
df_benefit["expected_monthly_benefit"] = (
    df_benefit.apply(
        calculate_expected_benefit,
        axis=1
    )
)

## 6. 카드별 종합 계산

In [16]:
card_result = (
    df_benefit
    .groupby("card_name")["expected_monthly_benefit"]
    .sum()
    .reset_index()
)

card_result = card_result.sort_values(
    "expected_monthly_benefit",
    ascending=False
)

display(card_result.head(20))

                         card_name  expected_monthly_benefit
77       [IBK기업은행] 참! 좋은 다이소카드(신용)                    264000
114                [iM뱅크] 그린카드(전국)                    225000
43                 [BNK부산] REXⅡ 카드                    184500
130               [신한] 부자되세요 홈쇼핑카드                    182000
79             [IBK기업은행] 후불 하이패스카드                    180000
65   [IBK기업은행] K22 Mileage SKYPASS                    166000
66             [IBK기업은행] K22 Point                    166000
13                     [BC바로] 그린카드                    164000
73            [IBK기업은행] 용인시민카드(신용)                    141400
87               [NH농협] 아이행복카드(신용)                    141000
72                [IBK기업은행] 무민신용카드                    125000
75            [IBK기업은행] 일상의 기쁨(신용)                    125000
92               [SC제일] 국민행복카드(신용)                    116800
69            [IBK기업은행] 국민행복카드(신용)                    116500
84               [NH농협] 국민행복카드(신용)                    112500
91                   [SC제일] TIME카드                    109000
112              [iM뱅크] 국민행복카드(신용)                    107500
99                  [Sh수협] All드림카드                    106000
105               [iM뱅크] iM ONE 카드                    106000
119         [iM뱅크] 부자되세요 홈쇼핑카드(신용)                    105000

In [18]:
sample = df_benefit["spend_limit_map"].iloc[0]

print(sample)
print(type(sample))

for k, v in sample.items():
    print(k, type(k), v, type(v))

{300000: 6000, 600000: 8000}
<class 'dict'>
300000 <class 'int'> 6000 <class 'int'>
600000 <class 'int'> 8000 <class 'int'>

In [19]:
def calculate_expected_benefit_v2(row):

    spending = row["matched_spending"]
    rate = row["benefit_rate_v2"]
    limit_map = row["spend_limit_map"]

    if pd.isna(rate):
        return 0

    expected = spending * (rate / 100)

    applicable_limit = None

    if isinstance(limit_map, dict) and len(limit_map) > 0:

        spend_conditions = []

        for k, v in limit_map.items():

            # no_spend_condition 처리
            if k == "no_spend_condition":
                applicable_limit = v
                continue

            # key가 문자열이면 숫자로 변환
            try:
                spend_condition = int(k)
                limit = int(v)
                spend_conditions.append((spend_condition, limit))
            except:
                continue

        spend_conditions = sorted(spend_conditions, reverse=True)

        for spend_condition, limit in spend_conditions:
            if total_monthly_spending >= spend_condition:
                applicable_limit = limit
                break

    if applicable_limit is not None:
        expected = min(expected, applicable_limit)

    return round(expected)

In [20]:
df_benefit["expected_monthly_benefit"] = df_benefit.apply(
    calculate_expected_benefit_v2,
    axis=1
)

card_result = (
    df_benefit
    .groupby("card_name")["expected_monthly_benefit"]
    .sum()
    .reset_index()
    .sort_values("expected_monthly_benefit", ascending=False)
)

display(card_result.head(20))

                         card_name  expected_monthly_benefit
114                [iM뱅크] 그린카드(전국)                    225000
43                 [BNK부산] REXⅡ 카드                    184500
130               [신한] 부자되세요 홈쇼핑카드                    182000
79             [IBK기업은행] 후불 하이패스카드                    180000
65   [IBK기업은행] K22 Mileage SKYPASS                    166000
66             [IBK기업은행] K22 Point                    166000
13                     [BC바로] 그린카드                    164000
87               [NH농협] 아이행복카드(신용)                    141000
92               [SC제일] 국민행복카드(신용)                    111800
69            [IBK기업은행] 국민행복카드(신용)                    111500
91                   [SC제일] TIME카드                    109000
84               [NH농협] 국민행복카드(신용)                    107500
105               [iM뱅크] iM ONE 카드                    106000
99                  [Sh수협] All드림카드                    106000
119         [iM뱅크] 부자되세요 홈쇼핑카드(신용)                    105000
112              [iM뱅크] 국민행복카드(신용)                    102500
73            [IBK기업은행] 용인시민카드(신용)                    100500
77       [IBK기업은행] 참! 좋은 다이소카드(신용)                    100000
10                   [BC바로] KaPick                    100000
28                 [BNK경남] REXⅡ 카드                     86000

In [23]:
top_card = card_result.iloc[0]["card_name"]

display(df_benefit[df_benefit["card_name"] == top_card][[
    "benefit_title",
    "card_name",
    "benefit_category_final",
    "matched_spending",
    "benefit_rate_v2",
    "all_previous_month_spend",
    "spend_limit_map",
    "expected_monthly_benefit"
]])

,benefit_title,card_name,benefit_category_final,matched_spending,benefit_rate_v2,all_previous_month_spend,spend_limit_map,expected_monthly_benefit
633,에코머니 포인트 기본 적립 최대 0.8% 적립,[iM뱅크] 그린카드(전국),기본혜택 / 포인트,0,0.8,"[200000, 500000, 1000000, 1500000]",{},0
634,에코머니 포인트 추가 적립 최대 4% 적립,[iM뱅크] 그린카드(전국),포인트,0,4.0,"[200000, 500000, 1000000, 1500000]",{},0
635,대중교통 최대 20% 적립,[iM뱅크] 그린카드(전국),교통,80000,20.0,"[10000, 200000, 1000000]",{},16000
636,Sleepless In Seattle 10% 청구할인,[iM뱅크] 그린카드(전국),카페,70000,10.0,[],{},7000
637,공공시설 무료입장 또는 최대 50% 할인,[iM뱅크] 그린카드(전국),간편결제 / 포인트,200000,50.0,[],{},100000
638,탄소포인트제(에코마일리지) 연 최대 10만 포인트 적립,[iM뱅크] 그린카드(전국),여행·항공 / 포인트,0,NaN,[],{},0
639,친환경 제품 소비 최대 17% 적립,[iM뱅크] 그린카드(전국),간편결제 / 마트·편의점 / 쇼핑 / 포인트,600000,17.0,[],{},102000
640,에코머니 가맹점 최대 5% 적립,[iM뱅크] 그린카드(전국),포인트,0,5.0,[],{},0

In [24]:
import re
import pandas as pd

def convert_money_or_point(text):
    if pd.isna(text):
        return None
    
    text = str(text).replace(",", "").strip()
    
    # 5,000점 / 10,000점
    m = re.search(r"(\d+)\s*점", text)
    if m:
        return int(m.group(1))
    
    # 5,000원
    m = re.search(r"(\d+)\s*원", text)
    if m:
        return int(m.group(1))
    
    # 5천원
    m = re.search(r"(\d+(?:\.\d+)?)\s*천원", text)
    if m:
        return int(float(m.group(1)) * 1000)
    
    # 1만원
    m = re.search(r"(\d+(?:\.\d+)?)\s*만원", text)
    if m:
        return int(float(m.group(1)) * 10000)
    
    return None


def extract_limit_candidates_v2(text):
    if pd.isna(text):
        return []
    
    text = str(text)
    
    patterns = [
        r"\d{1,3}(?:,\d{3})+\s*점",
        r"\d{1,3}(?:,\d{3})+\s*원",
        r"\d+(?:\.\d+)?\s*천원",
        r"\d+(?:\.\d+)?\s*만원",
    ]
    
    found = []
    
    for p in patterns:
        for m in re.findall(p, text):
            value = convert_money_or_point(m)
            if value:
                found.append(value)
    
    return sorted(list(set(found)))

In [25]:
df_benefit["all_limit_candidates_v2"] = (
    df_benefit["full_text"]
    .apply(extract_limit_candidates_v2)
)

In [26]:
def remove_spend_from_limits_v2(row):
    limits = row["all_limit_candidates_v2"]
    spends = row["all_previous_month_spend"]
    
    if not isinstance(limits, list):
        limits = []
    if not isinstance(spends, list):
        spends = []
    
    return [x for x in limits if x not in spends]

df_benefit["monthly_limit_candidates_v2"] = df_benefit.apply(
    remove_spend_from_limits_v2,
    axis=1
)

In [27]:
def map_spend_to_limit_v2(row):
    spends = row["all_previous_month_spend"]
    limits = row["monthly_limit_candidates_v2"]
    
    if not isinstance(spends, list):
        spends = []
    if not isinstance(limits, list):
        limits = []
    
    if len(spends) == len(limits) and len(spends) > 0:
        return dict(zip(spends, limits))
    
    if len(spends) > 0 and len(limits) == 1:
        return {spend: limits[0] for spend in spends}
    
    if len(spends) == 0 and len(limits) > 0:
        return {"no_spend_condition": limits[0]}
    
    return {}

df_benefit["spend_limit_map_v2"] = df_benefit.apply(
    map_spend_to_limit_v2,
    axis=1
)

In [28]:
display(df_benefit[df_benefit["card_name"].str.contains("그린카드", na=False)][[
    "benefit_title",
    "benefit_rate_v2",
    "all_previous_month_spend",
    "monthly_limit_candidates_v2",
    "spend_limit_map_v2",
    "full_text"
]])

,benefit_title,benefit_rate_v2,all_previous_month_spend,monthly_limit_candidates_v2,spend_limit_map_v2,full_text
95,에코머니 포인트 적립 서비스,40.0,"[300000, 600000]","[300000, 600000]",{'no_spend_condition': 300000},[전기차/수소차 충전 최대 40%]\n포인트 적립 대상 충전소 그린카드 홈페이지 확...
96,친환경 자동차 충전 최대 40% 적립,40.0,"[300000, 600000]","[300000, 600000]",{'no_spend_condition': 300000},"■ 전기차, 수소차 충전\n(그린카드 홈페이지 또는 앱에서 포인트 적립 대상 충전소..."
97,공유 모빌리티 10% 적립,10.0,[],[],{},"■ 쏘카, 투루카, 카카오T바이크, 따릉이(서울), 누비자(창원), 어울링(세종)\..."
98,대중교통 10% 적립,10.0,[],[],{},"■ 버스, 지하철\n* 월 최대 5천포인트 적립\n* 공항리무진, 공항버스, 고속버..."
99,일반교통 10% 적립,10.0,[],[],{},"■ 고속버스\n* 월 최대 5천 포인트 적립\n* 고속버스터미널 매표소, 온라인 예..."
...,...,...,...,...,...,...
636,Sleepless In Seattle 10% 청구할인,10.0,[],[],{},커피 전문점 Sleepless In Seattle 상시 10% 청구할인\n서비스 제...
637,공공시설 무료입장 또는 최대 50% 할인,50.0,[],[],{},전국 공공시설 무료입장 또는 최대 50% 할인\n자세한 내용은 에코머니 홈페이지(\...
638,탄소포인트제(에코마일리지) 연 최대 10만 포인트 적립,NaN,[],[],{},가정 내 에너지 절약 시 5천점 ~ 10만점 적립\n자세한 내용은 에코머니 홈페이지...
639,친환경 제품 소비 최대 17% 적립,17.0,[],[],{},녹색/유기농 매장에서 친환경 제품 구입 시 1~17% 적립 (총 720여개)\n자세...
640,에코머니 가맹점 최대 5% 적립,5.0,[],[],{},에코머니 가맹점 이용 시 1~5% 적립\n자세한 내용은 에코머니 홈페이지(\nwww...

In [29]:
import re
import pandas as pd

def convert_limit_value(text):
    if pd.isna(text):
        return None
    
    text = str(text).replace(",", "").strip()
    
    # 5천포인트 / 5천점 / 5천원
    m = re.search(r"(\d+(?:\.\d+)?)\s*천\s*(?:원|점|포인트)", text)
    if m:
        return int(float(m.group(1)) * 1000)
    
    # 1만포인트 / 1만점 / 1만원
    m = re.search(r"(\d+(?:\.\d+)?)\s*만\s*(?:원|점|포인트)", text)
    if m:
        return int(float(m.group(1)) * 10000)
    
    # 5,000원 / 5,000점 / 5,000포인트
    m = re.search(r"(\d+)\s*(?:원|점|포인트)", text)
    if m:
        return int(m.group(1))
    
    return None


def extract_monthly_limits_strict(text):
    if pd.isna(text):
        return []
    
    text = str(text)
    
    # 줄 단위로 나눠서 '한도/최대'가 있는 줄만 우선 탐색
    lines = re.split(r"[\n|]", text)
    
    found = []
    
    for line in lines:
        line = line.strip()
        
        # 전월실적 줄은 제외
        if "전월" in line and "실적" in line:
            continue
        
        # 한도/최대/월 최대/적립한도/할인한도 있는 줄만 사용
        if not any(k in line for k in ["한도", "최대", "월 최대", "적립한도", "할인한도"]):
            continue
        
        patterns = [
            r"\d{1,3}(?:,\d{3})+\s*(?:원|점|포인트)",
            r"\d+(?:\.\d+)?\s*천\s*(?:원|점|포인트)",
            r"\d+(?:\.\d+)?\s*만\s*(?:원|점|포인트)"
        ]
        
        for p in patterns:
            for m in re.findall(p, line):
                value = convert_limit_value(m)
                if value:
                    found.append(value)
    
    return sorted(list(set(found)))

In [30]:
df_benefit["monthly_limit_candidates_v3"] = (
    df_benefit["full_text"]
    .apply(extract_monthly_limits_strict)
)

In [31]:
def map_spend_to_limit_v3(row):
    spends = row["all_previous_month_spend"]
    limits = row["monthly_limit_candidates_v3"]
    
    if not isinstance(spends, list):
        spends = []
    if not isinstance(limits, list):
        limits = []
    
    # 전월실적별 한도가 같은 개수로 잡히면 순서대로 매핑
    if len(spends) == len(limits) and len(spends) > 0:
        return dict(zip(spends, limits))
    
    # 실적은 여러 개인데 한도가 1개면 공통 한도
    if len(spends) > 0 and len(limits) == 1:
        return {spend: limits[0] for spend in spends}
    
    # 실적 조건 없이 한도만 있으면
    if len(spends) == 0 and len(limits) > 0:
        return {"no_spend_condition": limits[0]}
    
    return {}

df_benefit["spend_limit_map_v3"] = df_benefit.apply(
    map_spend_to_limit_v3,
    axis=1
)

In [32]:
display(df_benefit[df_benefit["card_name"].str.contains("그린카드", na=False)][[
    "benefit_title",
    "benefit_rate_v2",
    "all_previous_month_spend",
    "monthly_limit_candidates_v3",
    "spend_limit_map_v3",
    "full_text"
]])

,benefit_title,benefit_rate_v2,all_previous_month_spend,monthly_limit_candidates_v3,spend_limit_map_v3,full_text
95,에코머니 포인트 적립 서비스,40.0,"[300000, 600000]","[5000, 20000]",{'no_spend_condition': 5000},[전기차/수소차 충전 최대 40%]\n포인트 적립 대상 충전소 그린카드 홈페이지 확...
96,친환경 자동차 충전 최대 40% 적립,40.0,"[300000, 600000]",[20000],{'no_spend_condition': 20000},"■ 전기차, 수소차 충전\n(그린카드 홈페이지 또는 앱에서 포인트 적립 대상 충전소..."
97,공유 모빌리티 10% 적립,10.0,[],[5000],{'no_spend_condition': 5000},"■ 쏘카, 투루카, 카카오T바이크, 따릉이(서울), 누비자(창원), 어울링(세종)\..."
98,대중교통 10% 적립,10.0,[],[5000],{'no_spend_condition': 5000},"■ 버스, 지하철\n* 월 최대 5천포인트 적립\n* 공항리무진, 공항버스, 고속버..."
99,일반교통 10% 적립,10.0,[],[5000],{'no_spend_condition': 5000},"■ 고속버스\n* 월 최대 5천 포인트 적립\n* 고속버스터미널 매표소, 온라인 예..."
...,...,...,...,...,...,...
636,Sleepless In Seattle 10% 청구할인,10.0,[],[],{},커피 전문점 Sleepless In Seattle 상시 10% 청구할인\n서비스 제...
637,공공시설 무료입장 또는 최대 50% 할인,50.0,[],[],{},전국 공공시설 무료입장 또는 최대 50% 할인\n자세한 내용은 에코머니 홈페이지(\...
638,탄소포인트제(에코마일리지) 연 최대 10만 포인트 적립,NaN,[],[],{},가정 내 에너지 절약 시 5천점 ~ 10만점 적립\n자세한 내용은 에코머니 홈페이지...
639,친환경 제품 소비 최대 17% 적립,17.0,[],[],{},녹색/유기농 매장에서 친환경 제품 구입 시 1~17% 적립 (총 720여개)\n자세...
640,에코머니 가맹점 최대 5% 적립,5.0,[],[],{},에코머니 가맹점 이용 시 1~5% 적립\n자세한 내용은 에코머니 홈페이지(\nwww...